name: Deploy docs

on: 
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: unbuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Node.js 
        id: changesets
        uses: changesets/setup-node@v3
        with:
          publish: npm run release
        env:
          GH_TOKEN: ${{ github.actor }:${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN:
          NPM_TOKEN:
          TURBO_TOKEN:
          TURBO_TEAM:

      - run: npm ci

        